### ISSUE TITLE
Awesome Work!!

### ISSUE THREAD

**Issue by smitshah81** [mbernson/culinologie#6]
Hello,

Awesome Work and i really appreciate your efforts for this project.
I was searching for some cooking opensource website and i found this website.It is really Cool!!! 
I was digging into code and i found one import script in this project.

and import url was point to "/Volumes/elBulli1998-2002/uk/data/478.dat" and this file is missing.

if possible can you please upload this file? If you don't have this file then can you give me sample of this .dat file?

Purpose behind this to see how data import work and if possible make enhancement in import script.

Can you help me on this please?

**Comment by mbernson** [comment]
Sorry for my (very) late reply.

The import script was written as a one-off thing to import recipes from old CD-ROM's. Due to copyright, I cannot share those files. 
If you have any other public sources that you want to import recipes from, I'd be happy to discuss it though.

Thanks for your interest in this project. :)
